import 'package:flutter/material.dart';

import '../models/app_language.dart';
import '../services/language_service.dart';

class LanguageNotifier extends ChangeNotifier {
  final LanguageService _service;

  AppLanguage _language = AppLanguage.english;

  LanguageNotifier(this._service) {
    _initialize();
  }

  AppLanguage get current => _language;

  Locale get locale => _language.locale;

  List<Locale> get supportedLocales =>
      AppLanguage.values.map((lang) => lang.locale).toList();

  Future<void> _initialize() async {
    await _service.init();
    _language = _service.savedLanguage;
    notifyListeners();
  }

  Future<void> setLanguage(AppLanguage language) async {
    _language = language;
    notifyListeners();
    await _service.saveLanguage(language);
  }

  String translate(String key, [Map<String, String>? params]) {
    final map = _translations[_language] ?? {};
    var template = map[key] ?? key;
    if (params != null) {
      params.forEach((placeholder, value) {
        template = template.replaceAll('{$placeholder}', value);
      });
    }
    return template;
  }
}

const Map<AppLanguage, Map<String, String>> _translations = {
  AppLanguage.english: {
    'app_title': 'ToDo Pro',
    'tooltip_toggle_sort': 'Toggle sort direction',
    'search_hint': 'Search tasks',
    'sort_label': 'Sort by:',
    'loading_tasks': 'Loading tasks...',
    'empty_tasks': 'No tasks yet.',
    'task_remove_title': 'Delete task',
    'task_remove_message': 'Are you sure you want to remove this task?',
    'dialog_cancel': 'Cancel',
    'dialog_delete': 'Delete',
    'status_done': 'Done',
    'status_pending': 'Pending',
    'filter_all': 'All',
    'filter_active': 'Active',
    'filter_completed': 'Completed',
    'filter_today': 'Today',
    'filter_overdue': 'Overdue',
    'sort_dueDate': 'Due date',
    'sort_createdAt': 'Creation date',
    'sort_priority': 'Priority',
    'task_form_new_title': 'New task',
    'task_form_edit_title': 'Edit task',
    'task_form_title_hint': 'Title',
    'task_form_description_hint': 'Description (optional)',
    'task_form_category_hint': 'Category',
    'task_form_recurrence_label': 'Recurrence',
    'task_form_interval_label': 'Every',
    'task_form_interval_hint': 'Example: 3',
    'task_form_due_label': 'Due: {date}',
    'task_form_due_add': 'Add due date',
    'task_form_due_remove': 'Remove due date',
    'task_form_save': 'Save',
    'task_form_save_changes': 'Save changes',
    'task_priority_low': 'Low',
    'task_priority_medium': 'Medium',
    'task_priority_high': 'High',
    'recurrence_none': 'Does not repeat',
    'recurrence_daily': 'Repeats every day',
    'recurrence_interval': 'Repeats every {interval} days',
    'recurrence_interval_choice': 'Custom interval',
    'legend_completed': 'Done',
    'legend_few': 'Few',
    'legend_none': 'None',
    'heatmap_panel_title': 'Yearly overview',
    'heatmap_panel_subtitle': 'Track your progress through the current year.',
    'heatmap_description':
        'Each star represents a completed task. Tap a column for details.',
    'heatmap_details_date': 'Date: {date}',
    'heatmap_details_header': '{count} tasks completed',
    'heatmap_details_empty': 'No tasks were completed on this date.',
    'stats_total_label': 'Total: {count}',
    'stats_progress_label': '{percent}% completed',
    'statistics_title': 'Statistics',
    'statistics_description': 'Track how many tasks you finished this year.',
    'statistics_hint': 'Tap a column to see details.',
    'task_remaining_overdue': 'Time expired',
    'task_remaining_hours': '{hours}h {minutes}m left',
    'task_remaining_minutes': '{minutes}m left',
    'task_remaining_now': 'Time is almost up',
    'language_section_button': 'Change language',
    'lock_prompt_title': 'Enter passcode',
    'lock_prompt_description': 'Enter your passcode to protect the app.',
    'lock_field_hint': 'Passcode',
    'lock_login_button': 'Unlock',
    'lock_error_empty': 'Enter a passcode',
    'lock_error_invalid': 'Incorrect passcode',
    'settings_title': 'Settings',
    'settings_description':
        'You can toggle reminder sounds here. Tap the switch to pick a new default for every reminder.',
    'toggle_title': 'Play reminder sound',
    'toggle_subtitle': 'Ring the alarm when a task is due',
    'toggle_info':
        'This preference affects all future reminders — change it anytime.',
    'lock_card_title': 'App lock',
    'lock_card_status_enabled': 'Enabled',
    'lock_card_status_disabled': 'Not set',
    'lock_card_description_enabled': 'Each launch requires your password.',
    'lock_card_description_disabled': 'Protect your tasks with a quick PIN.',
    'lock_card_button_primary': 'Set password',
    'lock_card_button_primary_update': 'Change password',
    'lock_card_button_secondary': 'Remove lock',
    'language_section_title': 'Interface language',
    'language_section_description':
        'English, Russian, Tajik, or Uzbek — pick the language you prefer.',
    'lock_dialog_title_new': 'App lock',
    'lock_dialog_title_update': 'Update password',
    'lock_dialog_password': 'Password',
    'lock_dialog_confirm': 'Confirm password',
    'lock_dialog_empty': 'Fill in both fields',
    'lock_dialog_mismatch': 'Passwords do not match',
    'lock_dialog_saved': 'Password saved',
    'lock_dialog_disable_title': 'Disable lock',
    'lock_dialog_disable_button': 'Remove',
    'lock_dialog_disable_success': 'Lock removed',
    'lock_dialog_disable_error': 'Incorrect password',
  },
  AppLanguage.russian: {
    'app_title': 'ToDo Pro',
    'tooltip_toggle_sort': 'Переключить сортировку',
    'search_hint': 'Поиск задач',
    'sort_label': 'Сортировка:',
    'loading_tasks': 'Загружаются задачи...',
    'empty_tasks': 'Пока нет задач.',
    'task_remove_title': 'Удалить задачу',
    'task_remove_message': 'Вы уверены, что хотите удалить задачу?',
    'dialog_cancel': 'Отмена',
    'dialog_delete': 'Удалить',
    'status_done': 'Выполнено',
    'status_pending': 'Ожидает',
    'filter_all': 'Все',
    'filter_active': 'Активные',
    'filter_completed': 'Выполненные',
    'filter_today': 'Сегодня',
    'filter_overdue': 'Просроченные',
    'sort_dueDate': 'Срок',
    'sort_createdAt': 'Дата добавления',
    'sort_priority': 'Приоритет',
    'task_form_new_title': 'Новая задача',
    'task_form_edit_title': 'Редактировать задачу',
    'task_form_title_hint': 'Название',
    'task_form_description_hint': 'Описание (необязательно)',
    'task_form_category_hint': 'Категория',
    'task_form_recurrence_label': 'Повторение',
    'task_form_interval_label': 'Каждые',
    'task_form_interval_hint': 'Например: 3',
    'task_form_due_label': 'Срок: {date}',
    'task_form_due_add': 'Добавить срок',
    'task_form_due_remove': 'Убрать срок',
    'task_form_save': 'Сохранить',
    'task_form_save_changes': 'Сохранить изменения',
    'task_priority_low': 'Низкий',
    'task_priority_medium': 'Средний',
    'task_priority_high': 'Высокий',
    'recurrence_none': 'Не повторяется',
    'recurrence_daily': 'Повторять каждый день',
    'recurrence_interval': 'Повторять каждые {interval} дней',
    'recurrence_interval_choice': 'Индивидуальный интервал',
    'legend_completed': 'Выполнено',
    'legend_few': 'Мало',
    'legend_none': 'Нет',
    'heatmap_panel_title': 'Итоги года',
    'heatmap_panel_subtitle': 'Следите за прогрессом в текущем году.',
    'heatmap_description':
        'Каждая точка — завершённая задача. Нажмите по колонке для деталей.',
    'heatmap_details_date': 'Дата: {date}',
    'heatmap_details_header': '{count} задач выполнено',
    'heatmap_details_empty': 'В этот день задач не завершено.',
    'stats_total_label': 'Всего: {count}',
    'stats_progress_label': '{percent}% выполнено',
    'statistics_title': 'Статистика',
    'statistics_description':
        'Отслеживайте, сколько задач завершено в этом году.',
    'statistics_hint': 'Нажмите на колонку, чтобы посмотреть детали.',
    'task_remaining_overdue': 'Время вышло',
    'task_remaining_hours': '{hours}ч {minutes}м осталось',
    'task_remaining_minutes': '{minutes}м осталось',
    'task_remaining_now': 'Время почти вышло',
    'language_section_button': 'Изменить язык',
    'lock_prompt_title': 'Введите пароль',
    'lock_prompt_description': 'Введите пароль, чтобы защитить приложение.',
    'lock_field_hint': 'Пароль',
    'lock_login_button': 'Разблокировать',
    'lock_error_empty': 'Введите пароль',
    'lock_error_invalid': 'Неверный пароль',
    'settings_title': 'Настройки',
    'settings_description':
        'Включайте или выключайте звук напоминаний здесь. Кнопка задаёт значение по умолчанию для всех новых напоминаний.',
    'toggle_title': 'Проигрывать звук напоминания',
    'toggle_subtitle': 'Сигнал прозвучит, когда задача станет просроченной',
    'toggle_info': 'Это изменение влияет на все будущие напоминания.',
    'lock_card_title': 'Блокировка',
    'lock_card_status_enabled': 'Включена',
    'lock_card_status_disabled': 'Не задана',
    'lock_card_description_enabled': 'Каждый запуск просит пароль.',
    'lock_card_description_disabled': 'Защитите задачи паролем.',
    'lock_card_button_primary': 'Установить пароль',
    'lock_card_button_primary_update': 'Изменить пароль',
    'lock_card_button_secondary': 'Снять блокировку',
    'language_section_title': 'Язык интерфейса',
    'language_section_description':
        'Выберите английский, русский, таджикский или узбекский для текста.',
    'lock_dialog_title_new': 'Блокировка',
    'lock_dialog_title_update': 'Обновить пароль',
    'lock_dialog_password': 'Пароль',
    'lock_dialog_confirm': 'Подтвердите пароль',
    'lock_dialog_empty': 'Заполните оба поля',
    'lock_dialog_mismatch': 'Пароли не совпадают',
    'lock_dialog_saved': 'Пароль сохранён',
    'lock_dialog_disable_title': 'Отключить блокировку',
    'lock_dialog_disable_button': 'Удалить',
    'lock_dialog_disable_success': 'Блокировка снята',
    'lock_dialog_disable_error': 'Неверный пароль',
  },
  AppLanguage.tajik: {
    'app_title': 'ToDo Pro',
    'tooltip_toggle_sort': 'Тартибро иваз кунед',
    'search_hint': 'Вазифаҳоро ҷустуҷӯ кунед',
    'sort_label': 'Тартиб:',
    'loading_tasks': 'Вазифаҳо боргирӣ мешаванд...',
    'empty_tasks': 'Ҳанӯз вазифа вуҷуд надорад.',
    'task_remove_title': 'Вазифаро нест кунед',
    'task_remove_message': 'Оё шумо итминон доред, ки ин вазифаро нест кунед?',
    'dialog_cancel': 'Бекор кардан',
    'dialog_delete': 'Нест кардан',
    'status_done': 'Бажарилган',
    'status_pending': 'Кутилмоқда',
    'filter_all': 'Ҳама',
    'filter_active': 'Фаъол',
    'filter_completed': 'Бажарилганҳо',
    'filter_today': 'Имрӯз',
    'filter_overdue': 'Мӯҳлат гузашта',
    'sort_dueDate': 'Мӯҳлат',
    'sort_createdAt': 'Вақти эҷод',
    'sort_priority': 'Аҳамият',
    'task_form_new_title': 'Вазифаи нав',
    'task_form_edit_title': 'Вазифаро таҳрир кунед',
    'task_form_title_hint': 'Сарлавҳа',
    'task_form_description_hint': 'Тавсиф (ихтиёрӣ)',
    'task_form_category_hint': 'Категория',
    'task_form_recurrence_label': 'Такроршавӣ',
    'task_form_interval_label': 'Ҳар',
    'task_form_interval_hint': 'Масалан: 3',
    'task_form_due_label': 'Мӯҳлат: {date}',
    'task_form_due_add': 'Мӯҳлат илова кунед',
    'task_form_due_remove': 'Мӯҳлатро нест кунед',
    'task_form_save': 'Сабт',
    'task_form_save_changes': 'Тағйиротро сабт кунед',
    'task_priority_low': 'Кам',
    'task_priority_medium': 'Миёна',
    'task_priority_high': 'Баланд',
    'recurrence_none': 'Такрор намешавад',
    'recurrence_daily': 'Ҳар рӯз такрор мешавад',
    'recurrence_interval': 'Ҳар {interval} рӯз такрор мешавад',
    'recurrence_interval_choice': 'Фосилаи фармоишӣ',
    'legend_completed': 'Бажарилган',
    'legend_few': 'Кам',
    'legend_none': 'Ҳеҷ',
    'heatmap_panel_title': 'Андозагирии солона',
    'heatmap_panel_subtitle':
        'Дар тӯли соли ҷорӣ пешравиҳоро пайгирӣ кунед.',
    'heatmap_description':
        'Ҳар ситора як вазифаи анҷомёфтаро нишон медиҳад. Барои тафсилот ба сутунҳо ламс кунед.',
    'heatmap_details_date': 'Сана: {date}',
    'heatmap_details_header': '{count} вазифа анҷом ёфт',
    'heatmap_details_empty': 'Дар ин рӯз вазифае анҷом дода нашудааст.',
    'stats_total_label': 'Ҷамъ: {count}',
    'stats_progress_label': '{percent}% иҷро шуд',
    'statistics_title': 'Статистика',
    'statistics_description':
        'Бубинед, ки дар ин сол чанд вазифа анҷом дода шуд.',
    'statistics_hint': 'Барои дидани тафсилот ба сутун ламс кунед.',
    'task_remaining_overdue': 'Вақт гузаштааст',
    'task_remaining_hours': '{hours}с {minutes}м мондааст',
    'task_remaining_minutes': '{minutes}м мондааст',
    'task_remaining_now': 'Вақт наздик аст',
    'language_section_button': 'Забонро иваз кунед',
    'lock_prompt_title': 'Рамзро ворид кунед',
    'lock_prompt_description': 'Барои ҳифзи барнома рамзро ворид кунед.',
    'lock_field_hint': 'Рамз',
    'lock_login_button': 'Қулфро кушоед',
    'lock_error_empty': 'Рамзро ворид кунед',
    'lock_error_invalid': 'Рамз нодуруст аст',
    'settings_title': 'Танзимотҳо',
    'settings_description':
        'Садои огоҳиномаҳоро ин ҷо фаъол/хомӯш кунед. Ин танзим дар тамоми огоҳиномаҳои нав татбиқ мешавад.',
    'toggle_title': 'Садо ҳангоми огоҳӣ',
    'toggle_subtitle': 'Ҳангоми расидани муҳлат сигнал бозӣ мекунад',
    'toggle_info': 'Ин танзим барои ҳамаи огоҳиномаҳои оянда амал мекунад.',
    'lock_card_title': 'Қулфи барнома',
    'lock_card_status_enabled': 'Фаъол',
    'lock_card_status_disabled': 'Мӯътабар нашудааст',
    'lock_card_description_enabled':
        'Ҳар бор кушода шудани барнома маълумоти паролӣ мехоҳад.',
    'lock_card_description_disabled': 'Барномаро бо парол ҳифз кунед.',
    'lock_card_button_primary': 'Парол гузоред',
    'lock_card_button_primary_update': 'Паролро навсозӣ кунед',
    'lock_card_button_secondary': 'Қулфро нест кунед',
    'language_section_title': 'Забони интерфейс',
    'language_section_description':
        'Англисӣ, русӣ, тоҷикӣ ё ӯзбекӣ — забони маъмулро интихоб кунед.',
    'lock_dialog_title_new': 'Қулфи барнома',
    'lock_dialog_title_update': 'Паролро навсозӣ кунед',
    'lock_dialog_password': 'Парол',
    'lock_dialog_confirm': 'Паролро тасдиқ кунед',
    'lock_dialog_empty': 'Ҳар ду майдонро пур кунед',
    'lock_dialog_mismatch': 'Паролҳо мувофиқат надоранд',
    'lock_dialog_saved': 'Парол сабт шуд',
    'lock_dialog_disable_title': 'Қулфро бекор кунед',
    'lock_dialog_disable_button': 'Нест кунед',
    'lock_dialog_disable_success': 'Қулф бекор шуд',
    'lock_dialog_disable_error': 'Парол нодуруст аст',
  },
  AppLanguage.uzbek: {
    'app_title': 'ToDo Pro',
    'tooltip_toggle_sort': 'Saralash tartibini o‘zgartiring',
    'search_hint': 'Vazifalarni qidiring',
    'sort_label': 'Saralash:',
    'loading_tasks': 'Vazifalar yuklanmoqda...',
    'empty_tasks': 'Hozircha vazifalar yo‘q.',
    'task_remove_title': 'Vazifani o‘chirish',
    'task_remove_message': 'Ushbu vazifani o‘chirmoqchimisiz?',
    'dialog_cancel': 'Bekor qilish',
    'dialog_delete': 'O‘chirish',
    'status_done': 'Bajarilgan',
    'status_pending': 'Kutilmoqda',
    'filter_all': 'Hammasi',
    'filter_active': 'Faol',
    'filter_completed': 'Bajarilgan',
    'filter_today': 'Bugun',
    'filter_overdue': 'Muddati o‘tgan',
    'sort_dueDate': 'Muddat',
    'sort_createdAt': 'Yaratilgan vaqti',
    'sort_priority': 'Ustuvorlik',
    'task_form_new_title': 'Yangi vazifa',
    'task_form_edit_title': 'Vazifani o‘zgartirish',
    'task_form_title_hint': 'Sarlavha',
    'task_form_description_hint': 'Tavsif (ixtiyoriy)',
    'task_form_category_hint': 'Kategoriya',
    'task_form_recurrence_label': 'Takrorlash turi',
    'task_form_interval_label': 'Har',
    'task_form_interval_hint': 'Masalan: 3',
    'task_form_due_label': 'Muddat: {date}',
    'task_form_due_add': 'Muddat qo‘shish',
    'task_form_due_remove': 'Muddatni olib tashlash',
    'task_form_save': 'Saqlash',
    'task_form_save_changes': 'O‘zgarishlarni saqlash',
    'task_priority_low': 'Kam',
    'task_priority_medium': 'O‘rtacha',
    'task_priority_high': 'Yuqori',
    'recurrence_none': 'Takrorlanmaydi',
    'recurrence_daily': 'Har kuni takrorlanadi',
    'recurrence_interval': 'Har {interval} kunda takrorlanadi',
    'recurrence_interval_choice': 'Maxsus interval',
    'legend_completed': 'Bajarilgan',
    'legend_few': 'Kam',
    'legend_none': 'Hech',
    'heatmap_panel_title': 'Joriy yil holati',
    'heatmap_panel_subtitle':
        'Joriy yil davomida bajarilgan vazifalarni kuzatib boring.',
    'heatmap_description':
        'Har bir yulduz bajarilgan vazifani anglatadi. Ustunning ustiga bosib tafsilotlarni ko‘ring.',
    'heatmap_details_date': 'Sana: {date}',
    'heatmap_details_header': '{count} ta vazifa bajarildi',
    'heatmap_details_empty': 'Bu kunda vazifa bajarilmagan.',
    'stats_total_label': 'Umumiy: {count}',
    'stats_progress_label': '{percent}% bajarildi',
    'statistics_title': 'Statistika',
    'statistics_description':
        'Joriy yil davomida bajargan vazifalaringizni kuzatib boring.',
    'statistics_hint': 'Ustun ustiga bosib batafsil ko‘ring.',
    'task_remaining_overdue': 'Vaqt tugagan',
    'task_remaining_hours': '{hours} soat {minutes} daqiqa qoldi',
    'task_remaining_minutes': '{minutes} daqiqa qoldi',
    'task_remaining_now': 'Vaqt yaqinlashyapti',
    'language_section_button': 'Tilni o‘zgartirish',
    'lock_prompt_title': 'Parolni kiriting',
    'lock_prompt_description':
        'Ilovani himoya qilish uchun parol kiriting.',
    'lock_field_hint': 'Parol',
    'lock_login_button': 'Kirish',
    'lock_error_empty': 'Parolni kiriting',
    'lock_error_invalid': 'Parol noto‘g‘ri',
    'settings_title': 'Sozlamalar',
    'settings_description':
        "Bu yerda eslatma tovushini yoqib/o‘chirishingiz mumkin. Har bir yangi eslatma uchun tanlangan holat saqlanadi.",
    'toggle_title': 'Eslatma tovushini yoqing',
    'toggle_subtitle': 'Vazifa muddati kelganda signal yangraydi',
    'toggle_info': 'Bu sozlama barcha keyingi eslatmalarga taalluqli bo‘ladi.',
    'lock_card_title': 'Ilova qulfi',
    'lock_card_status_enabled': 'Faol',
    'lock_card_status_disabled': 'Belgilanmagan',
    'lock_card_description_enabled':
        'Har safar ilovaga kirish parolni talab qiladi.',
    'lock_card_description_disabled': 'Vazifalarni parol bilan himoya qiling.',
    'lock_card_button_primary': 'Parol o‘rnating',
    'lock_card_button_primary_update': 'Parolni yangilang',
    'lock_card_button_secondary': 'Qulfni olib tashlash',
    'language_section_title': 'Interfeys tili',
    'language_section_description':
        'Matnlarni ingliz, rus, tojik yoki o‘zbek tillarida ko‘ring.',
    'lock_dialog_title_new': 'Ilova qulfi',
    'lock_dialog_title_update': 'Parolni yangilang',
    'lock_dialog_password': 'Parol',
    'lock_dialog_confirm': 'Parolni tasdiqlang',
    'lock_dialog_empty': 'Ikkala maydonni to‘ldiring',
    'lock_dialog_mismatch': 'Parollar mos emas',
    'lock_dialog_saved': 'Parol saqlandi',
    'lock_dialog_disable_title': 'Qulfni o‘chirish',
    'lock_dialog_disable_button': 'O‘chirish',
    'lock_dialog_disable_success': 'Qulf pasaytirildi',
    'lock_dialog_disable_error': 'Parol noto‘g‘ri',
  },
};
